FROM node:12.2.0-alpine as server
ADD . /usr/src/server
WORKDIR /usr/src/server
COPY package.json /usr/src/server/package.json
ENV NODE_PATH=/usr/src/server/node_modules
ENV PATH=/usr/src/server/node_modules/.bin/:${PATH}
RUN npm install
CMD ["npm", "start"]
EXPOSE 4000

# prod
# FROM nginx:1.16.0-alpine
# COPY --from=server /usr/src/server /usr/share/nginx/html
# RUN rm /etc/nginx/conf.d/default.conf
# COPY nginx/nginx.conf /etc/nginx/conf.d
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
